---
# Upload
#   upload mapping rules
#   Example:
#      mapping_rules:
#       -   name: mapping_rule_1
#           file: "uploads/mapping_rules/<file-name>.js"
#           category:   InfoMap
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: aac/upload_mapping_rules
      tags: upload_mapping_rules
      