---
# Add
#   add interfaces by following inventory structure:
#   Example:
#      activation_keys:
#        - id: wga
#          code: "AAAA-BBBB-CCCC-DDDD-EEEE"
- hosts: all
  connection: local
  roles:
    - role: activate_modules
      tags: activate_modules
      