# playbook for exporting certificates
# Example inventory:
#  export_certificates:
#      kdb_id:     "{{ item.kdb_id }}"
#      cert_id:    "{{ item.cert_id }}"
#      filename:   "{{ inventory_dir }}/{{ item.filename }}"
---
- hosts: all
  connection: local
  roles:
    - role: base/export_certificates
      tags: export_certificates