---
# Running first steps if necessary
#     accept service agreements
#     set up LMI FIPS (may restart appliance)
#     change password
#     commit and restart LMI
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: base/first_steps
      tags: first_steps