---
# Add
#   add interfaces by following inventory structure:
#   Example:
#      fix_packs:
#        - file: uploads/fix_packs/90x_IFx.fixpack
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: base/install_fixpacks
      tags: install_fixpacks
      