---
# Configure
#   configure reverse proxy instances
#   Example:
#     instances:
#       -   inst_name: default
#           entries:
#               - { method: set, stanza: server, entry_name: server-name, value: default }
- hosts: all
  connection: local
  roles:
    - role: web/configure_reverseproxy_instances
      tags: configure_reverseproxy_instances
      