---
# create
#   Create sso key file
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  gather_facts: False
  roles:
    - role: create_sso_keys
      tags: create_sso_keys
