---
# upload
#   upload dynurl files
#   Example:
#     dynurl_files
#       - file: uploads/dynurl/dynurl.conf
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: web/upload_dynurl_files
      tags: upload_dynurl_files
