---
# upload
#   upload dynurl files
#   Example:
#     jmt_files
#       - filename: uploads/dynurl/dynurl.conf
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: web/upload_dynurl_files
      tags: upload_dynurl_files
